import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
// import ConvexClientProvider from "@/providers/ConvexClientProvider";

import { ClerkProvider, SignInButton, SignedIn, SignedOut, UserButton } from '@clerk/nextjs'
import { Button } from "@/components/ui/button";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
  
    <ClerkProvider>
      <html lang="en">
        <body>
          
          <header>
            <SignedOut>
             <Button><SignInButton /></Button>
            </SignedOut>
            <SignedIn>
              <UserButton />
            </SignedIn>
          </header>
          <main>
            {children}
          </main>
        </body>
      </html>
    </ClerkProvider>
     
  );
}
